[features]
seeds = false
skip-lint = false
[programs.mainnet]
aleph_solana_contract = "ALepH1n9jxScbz45aZhBYVa35zxBNbKSvL6rWQpb4snc"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = "/Users/riki/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
